#include "game/data.h"

// Item.c
s32 callAttackMotTbl[] = {
    DATA_MAKE_NUM(DATADIR_W01, 31),
    DATA_MAKE_NUM(DATADIR_W02, 5),
    DATA_MAKE_NUM(DATADIR_W03, 29),
    DATA_MAKE_NUM(DATADIR_W04, 9),
    DATA_MAKE_NUM(DATADIR_W05, 7),
    DATA_MAKE_NUM(DATADIR_W06, 19)
};

s32 callAttackMotTbl2[] = {
    DATA_MAKE_NUM(DATADIR_W01, 32),
    DATA_MAKE_NUM(DATADIR_W02, 6),
    DATA_MAKE_NUM(DATADIR_W03, 30),
    DATA_MAKE_NUM(DATADIR_W04, 10),
    DATA_MAKE_NUM(DATADIR_W05, 8),
    DATA_MAKE_NUM(DATADIR_W06, 20)
};